Controllers/ComuniController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using KampusStudio.Models.InputModels;
using KampusStudio.Models.Services.Application;
using KampusStudio.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace kampus.Controllers
{
    public class ComuniController : Controller
    {
        private readonly IComuneService comuneService;
        public ComuniController(IComuneService comuneService)
        {
            this.comuneService = comuneService;
        }
        public async Task<IActionResult> Index(ComuneElencoInputModel input)
        {
            ViewBag.Titolo = "Kampus Studio - Elenco comuni";
            ListViewModel<ComuneViewModel> comuni = await comuneService.GetComuniAsync(input);

            ComuneListViewModel viewModel = new ComuneListViewModel
            {
                Comuni = comuni,
                Input = input
            };

            return View(viewModel);
        }

        public async Task<IActionResult> Dettaglio(string id)
        {
            ComuneViewModel comune = await comuneService.GetComuneAsync(id);
            ViewBag.Titolo = "Kampus Studio - Comune di " + comune.nomeComune;
            return View(comune);
        }
    }
}

Controllers/ProvinceController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using KampusStudio.Models.Services.Application;
using KampusStudio.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace KampusStudio.Controllers
{
    public class ProvinceController : Controller
    {
        private readonly IProvinciaService provinciaService;
        public ProvinceController(IProvinciaService provinciaService)
        {
            this.provinciaService = provinciaService;
        }
        public async Task<IActionResult> Index()
        {
            ViewBag.Titolo = "Kampus Studio - Elenco province";
            List<ProvinciaViewModel> province = await provinciaService.GetProvinceAsync();
            return View(province);
        }

        public async Task<IActionResult> Dettaglio(int id)
        {
            ProvinciaViewModel provincia = await provinciaService.GetProvinciaAsync(id);
            ViewBag.Titolo = "Kampus Studio - Provincia " + provincia.nomeProvincia;
            return View(provincia);
        }
    }
}

Controllers/RegioniController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using KampusStudio.Models.Services.Application;
using KampusStudio.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Kampus.Controllers
{
    public class RegioniController : Controller
    {
        private readonly IRegioneService regioneService;
        public RegioniController(IRegioneService regioneService)
        {
            this.regioneService = regioneService;
        }
        public async Task<IActionResult> Index()
        {
            ViewBag.Titolo = "Kampus Studio - Elenco regioni";
            List<RegioneViewModel> regioni = await regioneService.GetRegioniAsync();
            return View(regioni);
        }

        public async Task<IActionResult> Dettaglio(int id)
        {
            RegioneViewModel regione = await regioneService.GetRegioneAsync(id);
            ViewBag.Titolo = "Kampus Studio - Regione " + regione.nomeRegione;
            return View(regione);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Titolo</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/a8715fafc0.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/style.css">
</head>
<body>
    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" asp-controller="Home"><img src="/logo.gif" height="30"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-controller="Home">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Geografia
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" asp-action="Index" asp-controller="Comuni">Comuni italiani</a>
                    <a class="dropdown-item" asp-action="Index" asp-controller="Regioni">Regioni</a>
                    <a class="dropdown-item" asp-action="Index" asp-controller="Province">Province</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Nazioni</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
        </ul>
        </div>
    </nav>
    </header>

    <div class="container">
        @RenderBody()
    </div>

    <footer>
        <p>Kampus Studio - Prototype version</p>
    </footer>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>